packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  hono: 4.6.20
  typescript: 5.7.3
  tailwindcss: 3.4.17
  "@types/node": 22.12.0

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": 19.0.4
    "@types/react-dom": 19.0.2
